### PR TITLE
Remove permission for Screenshot directory

### PR DESCRIPTION
**Pull request by JakobDev**
This permission causes this Directory to be created, but it is not used by RMG.

### CODE REVIEW

**Comment by Rosalie241** [comment]
The screenshots directory was changed in v0.5.7 to the one it is currently, the one before that used the one specified in the flatpak yml, I'd like to keep backwards compatability so it doesn't break for people who've used the RMG flatpak from before v0.5.7, would it be possible to do that by i.e removing the `:create` from the yml so it gives permission to that directory only when it exists?

**Comment by JakobDev** [comment]
I had it now changed from `create` to `rw`.

> The screenshots directory was changed in v0.5.7

I feel this is a better directory than saving Screenshots in some hidden directory.

**Comment by TingPing** [comment]
> so it gives permission to that directory only when it exists?

It may be confusing to users, because RMG will still save files there, they will just be on a tmpfs that gets lost. To fix this they have to make the directory before starting RMG.

**Comment by Rosalie241** [comment]
> It may be confusing to users, because RMG will still save files there, they will just be on a tmpfs that gets lost. To fix this they have to make the directory before starting RMG.

it wont be confusing to users because after v0.5.7 the default option was changed, so users who migrated from v0.5.6 to the latest version will still have a functional screenshots directory in their pictures directory, while new users will use the new default without having an unneeded directory created in their pictures directory.

**Comment by Rosalie241** [comment]
Thank you @JakobDev :heart:

**Pull request merged**
